### ISSUE TITLE
Request for Unreal Engine 5.4 support

### ISSUE THREAD

**Issue by tutmryan** [edgegap/edgegap-unreal-plugin#14]
**UE Version: **5.4

When will this plugin support 5.4? Considering 5.4's been out for a while now

Currently, if you try to build with 5.3, the plugin fails to compile with the following:
`
12>[1/5] Compile [x64] APITokenSettingsCustomization.cpp
12>E:\work\gamemaking\plugins\systems\FPS Multiplayer Template 5 UE5.3\FPSMultiplayerTemplate53\Plugins\Edgegap\Source\Edgegap\Private\APIToken\APITokenSettingsCustomization.cpp(50): error C2065: 'LLOCTEXT_NAMESPACE': undeclared identifier
12>E:\work\gamemaking\plugins\systems\FPS Multiplayer Template 5 UE5.3\FPSMultiplayerTemplate53\Plugins\Edgegap\Source\Edgegap\Private\APIToken\APITokenSettingsCustomization.cpp(51): error C2065: 'LLOCTEXT_NAMESPACE': undeclared identifier
12>E:\work\gamemaking\plugins\systems\FPS Multiplayer Template 5 UE5.3\FPSMultiplayerTemplate53\Plugins\Edgegap\Source\Edgegap\Private\EdgegapSettingsDetails.cpp(1563): warning C4996: 'FJsonObject::GetStringField': Passing an ANSI string to GetStringField has been deprecated outside of UTF-8 mode. Please use the overload that takes a TCHAR string. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
12>E:\work\gamemaking\plugins\systems\FPS Multiplayer Template 5 UE5.3\FPSMultiplayerTemplate53\Plugins\Edgegap\Source\Edgegap\Private\EdgegapSettingsDetails.cpp(1564): warning C4996: 'FJsonObject::GetStringField': Passing an ANSI string to GetStringField has been deprecated outside of UTF-8 mode. Please use the overload that takes a TCHAR string. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
12>E:\work\gamemaking\plugins\systems\FPS Multiplayer Template 5 UE5.3\FPSMultiplayerTemplate53\Plugins\Edgegap\Source\Edgegap\Private\EdgegapSettingsDetails.cpp(348): error C4702: unreachable code`
